### ISSUE TITLE
HIYA HIYA HIYA

### ISSUE THREAD

**Issue by adzkar** [bhrdn/IMPAL#1]
![Duar](https://4.bp.blogspot.com/-yWvG0EOPIP4/XVnYJqTCcxI/AAAAAAAAAbc/R-qzXjbBoSYiy3lX6IZ1kbEJ1-oRACSBwCLcBGAs/s1600/Arti-duar-meme.jpg "Duar")

**Comment by bhrdn** [comment]
![image](https://user-images.githubusercontent.com/13828056/63822048-4fe2cc00-c979-11e9-930d-bf9151c6d8a1.png)
